Update thermal control design document
Junchao-Mellanox/SONiC pull request #2
Opened 2020-03-02 09:05 UTC by Junchao-Mellanox

1. Update json configuration file with latest format
2. Add description for how to implement thermal policy
3. Update command line out put

2020-03-05 06:09 UTC, Junchao-Mellanox commented
@keboliu please help review.

2020-03-11 10:54 UTC, keboliu requested changes

2020-03-11 10:54 UTC, keboliu commented on thermal-control-design.md
> +- If there are fans without drawer, we still add a drawer object for each of fan, and consider the drawer only has one fan.
we need to handle this "virtual" fan drawer object carefully, we don't want to have this virtual fan drawer information to be showed in CLI.

2020-03-11 10:54 UTC, keboliu commented on thermal-control-design.md
>  3. Is there any API exposed for fanTray contain more than one fan?
this line can be removed since now we are adding a fan drawer(fan tray)

2020-03-11 10:54 UTC, keboliu commented on thermal-control-design.md
> +In current implementation, fan led management API is based on fan object. However, in many hardware platform, multiple fans are put in a fan drawer, they share one fan led. In such case, to control f
shall we extract fan drawer design as a separated section?

2020-03-11 10:54 UTC, keboliu commented on thermal-control-design.md
> +	FAN 2  60%        Exhaust    Not Present  Not OK  20191112 09:38:16
we shall update the show command output to reflect fan drawer info.  and also DB schema need to be changed to have fan drawer info, right?

2020-03-18 10:43 UTC, keboliu commented on thermal-control-design.md
> +	           FAN 2  60%        intake     Present      OK      20191112 09:38:16
Need to add Drawer name to each of it's fan, I believe we have the case that fan doesn't have a drawer, we need to distinguish these two cases.

2020-03-18 10:47 UTC, keboliu commented on thermal-control-design.md
> +In current implementation, fan led management API is based on fan object. However, in many hardware platform, multiple fans are put in a fan drawer, they share one fan led. In such case, to control f
I think adding fan drawer is not only for led,  it also gives information about real HW layout, which fan are in which drawer.

2020-03-18 10:51 UTC, keboliu commented on thermal-control-design.md
> +- If there are fans without drawer, we still add a virtual drawer object for each of fan, and consider the drawer only has one fan. We don't show virtual drawer in CLI.
should make it clear that thermalctld go through drawer first, so have to have a virtual drawer object even no drawer.

2020-03-29 07:37 UTC, keboliu approved these changes

2020-03-30 02:19 UTC, closed without merging